# Generated by Django 3.1.1 on 2020-09-11 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_category', models.CharField(max_length=80)),
                ('blog_summary', models.CharField(max_length=100)),
                ('category_slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_series', models.CharField(max_length=100)),
                ('series_summary', models.CharField(max_length=100)),
                ('blog_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='blogapp.blogcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=40)),
                ('blog_summary', models.TextField()),
                ('blog_content', models.TextField()),
                ('blog_published', models.DateField(default=datetime.datetime(2020, 9, 11, 16, 35, 21, 482990), verbose_name='date post')),
                ('blog_slug', models.CharField(max_length=80)),
                ('blog_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='blogapp.blogseries', verbose_name='Series')),
            ],
        ),
    ]
