# Generated by Django 3.1.1 on 2020-09-11 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_published',
            field=models.DateField(default=datetime.datetime(2020, 9, 11, 16, 39, 21, 756619), verbose_name='date post'),
        ),
        migrations.AlterField(
            model_name='blogseries',
            name='series_summary',
            field=models.CharField(max_length=250),
        ),
    ]
