# Generated by Django 3.1.1 on 2020-09-11 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200911_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_summary',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_published',
            field=models.DateField(default=datetime.datetime(2020, 9, 11, 16, 42, 13, 742658), verbose_name='date post'),
        ),
    ]
