# Generated by Django 3.1.1 on 2020-09-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200930_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='blog_summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogseries',
            name='series_summary',
            field=models.TextField(),
        ),
    ]
