# Generated by Django 3.1.1 on 2020-10-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20200930_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user_name',
            field=models.CharField(default='Vikash Singh', max_length=30),
        ),
    ]
